### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by chrfel** [Florian0301/OOP-Praktika#1]
Moin Flo!
Die "+1" an der Stelle muss weg, ansonsten geht man über die Liste hinaus und current ist null 😎 

https://github.com/Florian0301/OOP-Praktika/blob/1d1f2056eddd50aadb5c6affe08bdbfc467e8140/OOP%20Praktika/src/praktikum2/VokabelTrainer.java#L295

**Comment by Florian0301** [comment]
fixed
