### ISSUE TITLE
nextLine()

### ISSUE THREAD

**Issue by chrfel** [Florian0301/OOP-Praktika#2]
Hier muss es an beiden Stellen nextLine() sein, ansonsten erkennt er z.B. "to eat" nicht komplett :)

https://github.com/Florian0301/OOP-Praktika/blob/7fd2feed052e382a74576064ab7e3a1746048424/OOP%20Praktika/src/praktikum2/VokabelTrainer.java#L302

https://github.com/Florian0301/OOP-Praktika/blob/7fd2feed052e382a74576064ab7e3a1746048424/OOP%20Praktika/src/praktikum2/VokabelTrainer.java#L314

**Comment by Florian0301** [comment]
an mehreren stellen angepasst
